"""add should_delete

Revision ID: 5462b430c9b2
Revises: ab0f36e21e87
Create Date: 2024-05-16 19:01:03.903860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5462b430c9b2'
down_revision: Union[str, None] = 'ab0f36e21e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('should_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'should_delete')
    # ### end Alembic commands ###
