"""add format field

Revision ID: ebf0b21f86b5
Revises: ad03762fd216
Create Date: 2024-05-07 21:34:37.180252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf0b21f86b5'
down_revision: Union[str, None] = 'ad03762fd216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('format', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'format')
    # ### end Alembic commands ###
