"""remove file_uuid

Revision ID: efd118eebd72
Revises: 70229bc478d2
Create Date: 2025-01-09 20:08:00.314031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd118eebd72'
down_revision: Union[str, None] = '70229bc478d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
